    <!DOCTYPE html>
    <html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        <meta name="description" content="">
        <meta name="Sam" content="">

        <title>Luanda SAA</title>

        <!-- Bootstrap Core CSS -->
        <link href="<?= PATH?>public/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="<?= PATH?>public/css/simple-sidebar.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <style type="text/css">
            
            fieldset {
    font-family: sans-serif;
    border: 5px solid #1F497D;
    background: #ddd;
    border-radius: 5px;
    padding: 15px;
}

fieldset legend {
    background: #1F497D;
    color: #fff;
    padding: 5px 10px ;
    font-size: 32px;
    border-radius: 5px;
    box-shadow: 0 0 0 5px #ddd;
    margin-left: 20px;
}
        </style>

    </head>

    <body>

        <div id="wrapper">

            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#">
                        ANGOLA
                        </a>
                    </li>
                    <li>
                        <a href="<?= PATH?>" alt="Agendar">Agendar</a>
                    </li>
                    <li>
                        <a href="<?= PATH?>/reagendar">Reagendar</a>
                    </li>
                    <li>
                        <a href="<?= PATH ?>/cancelar">Cancelar</a>
                    </li>
                   
                </ul>
            </div>
            <!-- /#sidebar-wrapper -->

            <!-- Page Content -->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1>SAA - Sistema de Atendimento Agendado</h1>
                            <h3>Informe seus dados</h3>
                           <hr>
                             
                        </div>
                    </div>

                    <form class="form-horizontal" method="GET" action="<?= PATH?>agendar/">
    <fieldset>

    <!-- Form Name -->
    <legend>Agendamento- Informe seus dados </legend>

    <!-- Select Basic -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="municipio">Município</label>
      <div class="col-md-4">
        <select id="municipio" name="municipio" class="form-control">
          <option value="1">Cazenga</option>
          <option value="2">Icolo</option>
        </select>
      </div>
    </div>

    <!-- Select Basic -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="selectbasic">Provincia</label>
      <div class="col-md-4">
        <select id="selectbasic" name="selectbasic" class="form-control">
          <option value="1">Luanda</option>
          <option value="2">Benguela</option>
        </select>
      </div>
    </div>

    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="prosseguir"></label>
      <div class="col-md-4">
        <button id="prosseguir" name="prosseguir" class="btn btn-primary">Prosseguir</button>
      </div>
    </div>

    </fieldset>
    </form>

                </div>
            </div>
            <!-- /#page-content-wrapper -->

        </div>
        <!-- /#wrapper -->

        <!-- jQuery -->
        <script src="<?= PATH?>public/js/jquery.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="<?= PATH?>public/js/bootstrap.min.js"></script>

        <!-- Menu Toggle Script -->
        <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
        </script>

    </body>

    </html>
