<div ng-controller="homeController" >

    <form class="form-horizontal"  ng-submit="verificar(data)" method="POST">
    <fieldset>

    <!-- Form Name -->
    <legend>  {{error || "Informações do Agendamento"}}     </legend>

  <!-- Select Basic -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="selectbasic">Provincia</label>
      <div class="col-md-4">
        <select id="provincia" name="provincia" class="form-control" ng-model="data.provincia">
          <option value="1">Luanda</option>
          <option value="2">Benguela</option>
        </select>
      </div>
    </div>

    <!-- Select Basic -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="municipio">Município</label>
      <div class="col-md-4">
        <select id="municipio" name="municipio" class="form-control" ng-model="data.municipio">
          <option value="1">Cazenga</option>
          <option value="2">Icolo</option>
        </select>
      </div>
    </div>

  
    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="prosseguir"></label>
      <div class="col-md-4">
        <button id="prosseguir" name="prosseguir" class="btn btn-primary">Prosseguir</button>
      </div>
    </div>

    </fieldset>
    </form>

                </div>
          