   
    <div class="alert alert-danger fade in" ng-if="error">

        
        <strong>Aviso! </strong> {{error}}

    </div>
    
<div ui-calendar="uiConfig.calendar" ng-model="calendarDate" calendar="myCalendar"></div>
    
<div class="container-fluid">
  <div class="row">
      
        <div class="col-md-6 text-right">
        <button type="button" class="btn btn-primary custom-button-width .navbar-right" ng-click="avancar()">Avançar</button>
      
      </div>
  </div>
</div>
    